/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Handbook Introduction',
      collapsed: false,
      link: {
        type: 'doc',
        id: '00-handbook-introduction/what-is-genai-llm',
      },
      items: [
        {type: 'autogenerated', dirName: '00-handbook-introduction'},
      ],
    },
    {
      type: 'category',
      label: 'Handbook Method',
      collapsed: false,
      items: [
        '01-handbook-method/01-overview',
        '01-handbook-method/02-ideation-and-use-case',
        '01-handbook-method/03-model-selection',
        '01-handbook-method/cost-intuition',
        '01-handbook-method/cheat-sheet',
        '01-handbook-method/discovery-brief',
        '01-handbook-method/the-genai-llm-loop',
        '01-handbook-method/genai-llm-loop-spec',
        '01-handbook-method/working-agreements-for-teams',
        '01-handbook-method/intent-spec',
        '01-handbook-method/constraint-spec',
        '01-handbook-method/delegation-contract',
        '01-handbook-method/generation-requests',
        '01-handbook-method/review-and-interrogation',
        '01-handbook-method/acceptance-criteria',
        '01-handbook-method/iteration-and-release',
        '01-handbook-method/accountability-and-delegation',
        '01-handbook-method/artifact-contracts',
        '01-handbook-method/risks-production-challenges',
        '01-handbook-method/prompt-engineering',
        '01-handbook-method/instruction-tuning',
        '01-handbook-method/fine-tuning',
        '01-handbook-method/peft',
        '01-handbook-method/05-rag',
        '01-handbook-method/07-tool-use-and-agents',
        '01-handbook-method/testing-tools',
        '01-handbook-method/evaluation',
        {
          type: 'category',
          label: 'Core Skills',
          items: [{type: 'autogenerated', dirName: '01-handbook-method/core-skills'}],
        },
        {
          type: 'category',
          label: 'Evaluation Library',
          items: [{type: 'autogenerated', dirName: '01-handbook-method/08-evaluation'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Execution Patterns',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '02-execution-patterns'}],
    },
    {
      type: 'category',
      label: 'Professional Scenarios',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '03-professional-scenarios'}],
    },
    {
      type: 'category',
      label: 'Tooling & Frameworks',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '04-tooling-and-frameworks'}],
    },
    {
      type: 'category',
      label: 'Responsible AI',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '05-responsible-ai'}],
    },
    {
      type: 'category',
      label: 'Foundations',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'foundations/01-generative-ai-introduction/introduction',
      },
      items: [
        {
          type: 'category',
          label: 'Generative AI Basics',
          items: [{type: 'autogenerated', dirName: 'foundations/01-generative-ai-introduction'}],
        },
        {
          type: 'category',
          label: 'NLP Core Concepts',
          items: [{type: 'autogenerated', dirName: 'foundations/03-nlp-basics'}],
        },
        {
          type: 'category',
          label: 'Sequential Models',
          items: [{type: 'autogenerated', dirName: 'foundations/04-sequential-models'}],
        },
        {
          type: 'category',
          label: 'Attention & Transformers',
          items: [{type: 'autogenerated', dirName: 'foundations/05-attention-and-transformers'}],
        },
        {
          type: 'category',
          label: 'LLM Deep Dive',
          items: [{type: 'autogenerated', dirName: 'foundations/02-llm-deep-dive'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '06-templates'}],
    },
    {
      type: 'doc',
      id: 'AGENTS',
      label: 'CLI Agents (General)',
    },
    {
      type: 'doc',
      id: 'CHANGELOG',
      label: 'Changelog',
    },
    {
      type: 'doc',
      id: 'LICENSE',
      label: 'License',
    },
  ],
};

module.exports = sidebars;
